### ISSUE TITLE
decision tables for herring

### ISSUE THREAD

**Issue by jaclyncleary** [pbs-assess/gfiscam#11]
Chris- this is the decision table format I used for herring in 2016. 
![Uploading decisiontableHG.png…]()

I'd like something similar for this year. Last year both AM1 and AM2 model formulations are included in the same decision table. These can also be two separate tables if this is too tricky (I was just trying to save space). The columns for **AM1** need to be:
1) TAC (metric tonnes)
2) Prob (biomass after harvest is below LRP of 0.30SB0 in 2018) || P(SB2018 < 0.30SB0)
3) Median ratio of projected post-harvest biomass to 0.30SB0 || Med (SB2018/ 0.30SB0)
4) Prob (removal rate > target HR)  ||  P(U’2018 >20%)
5) Prob (removal rate > target HR)  ||  P(U’2018 >10%)
6) Prob (removal rate > target HR)  ||  P(U’2018 >5%)
7) Median removal rate  ||  Med (U’2018)

The columns for **AM2** need to be:
1) TAC (metric tonnes)
2) Prob (biomass after harvest is below LRP of 0.30SB0 in 2018) || P(SB2018 < 0.30SB0)
3) Median ratio of projected post-harvest biomass to 0.30SB0 || Med (SB2018/ 0.30SB0)
4) Prob (biomass after harvest is below cut-off in 2018  ||  P(SB2017 < 10,700 t)
5) Median ratio of projected post-harvest biomass to cut-off  ||  Med (SB2018/ 10,700 t)
** where  the fixed cut-off value is stock specific:
HG - 10,700 t
PRD - 12,100 t
CC - 17,600 t
SOG - 21,200 t
WCVI - 18,800 t

6) Prob (removal rate > target HR)  ||  P(U’2018 >20%)
7) Prob (removal rate > target HR)  ||  P(U’2018 >10%)
8) Prob (removal rate > target HR)  ||  P(U’2018 >5%)
9) Median removal rate  ||  Med (U’2018)

**Comment by jaclyncleary** [comment]
<img width="1036" alt="decisiontablehg" src="https://user-images.githubusercontent.com/2219398/30278103-71298a9c-96be-11e7-874b-7fad2221b6c4.png">

**Comment by cgrandin** [comment]
Thanks.. I am going through all issues now. I will finish the M output for iscam-pbs first
