### ISSUE TITLE
comparing MPD estimates of SB_0 between sensitivity runs of kappa and rho

### ISSUE THREAD

**Issue by jaclyncleary** [pbs-assess/gfiscam#12]
I would like to compare SB_0 values from the MPD estimation between sensitivity runs of kappa and rho. This could be table of MPD values, but I'd prefer to use a figure. Is it enough to plot single MPD values or is there a measure of variance in MPD estimates that is captured in admb output that I can use?

**Comment by robynforrest** [comment]
Just use single values

**Comment by jaclyncleary** [comment]
ok, thx Robyn
