### ISSUE TITLE
Generate file 'commandline.mcmc.'

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/gfiscam#13]
This file is produced in iSCAM Version 1 to indicate the number of MCMC runs, burn-in, and thinning. These would be useful for making variables in the res-doc knitr script. Not high priority.

**Comment by jaclyncleary** [comment]
Sarah- can you check- I think this might be saved in another format in V2...

**Comment by cgrandin** [comment]
Currently for the document the variables for these are set manually in custom-knitr-variables.r

**Comment by grinnellm** [comment]
Thanks Chris, the manual approach is fine for now. It would be useful to have these set automagically at some point.. but like I said, it's not high priority:)
