### ISSUE TITLE
gamma distribution in ctl file (minor edit/clarification)

### ISSUE THREAD

**Issue by jaclyncleary** [pbs-assess/gfiscam#14]
In the ctl file the gamma distribution lists moments as p1=alpha and p2=beta. Are these actually alpha and beta or k and theta?  where alpha=k (shape parameter) and beta=1/theta, where theta is the scale parameter.  My hunch is the p1=alpha and p2=beta was copied from the description of the beta distribution, but it would be worth checking at some point...

**Comment by cgrandin** [comment]
I've checked and it's dgamma() from statsLib. So yes cut and paste mistake..

/**
* \date 2/28/2011
* \author Steven Martell
* \param x is the quantile and must be greater than 0.
* \param a is the shape parameter and must be positive.
* \param b is the rate parameter and must be positive.
* \return a dvariable object
* \sa
**/

**Comment by jaclyncleary** [comment]
thanks
