### ISSUE TITLE
running slowMSY to calculate Fmsy

### ISSUE THREAD

**Issue by jaclyncleary** [pbs-assess/gfiscam#15]
to run slowMSY, for herring, we need to use Fmax=3 (and associated ctl switches)

do we only run the MPD estimation? or the mcmc?

where do the f-values get outputted? I want to "see" the histogram and "see" that the Fmsy value appears at the peak.

**Comment by robynforrest** [comment]
I don't recommend running it in mceval model if you are setting Fmax=3.

There is a file called Test_FRP,rep  (or something similar). plot Ye, this is the yield curve.  I don't have my work computer with me but I think this is what you need

**Comment by cgrandin** [comment]
Yes slow_msy is only for the MPD.. when you turn it on you should see a file called TEST_frp.rep appear which has the values you want. They're not formatted for plotting but you should be able to see where it changes

**Comment by jaclyncleary** [comment]
okay so we're seeing the Ye values and associated Fmsy values. The estimates we get from the slow MSY code are very different from those included in the LRP paper. Eg, 1.01 (slowMSY) vs. 0.55. Sarah and I will go over this again and see if we can figure out where we've gone awry...

**Comment by robynforrest** [comment]
The LRP calculations did not account for spawn timing so I wouldn't expect them to be the same. They are all tested. Check against the spreadsheet to make sure.

**Comment by robynforrest** [comment]
I mean the iscam calcs are all tested

**Comment by jaclyncleary** [comment]
that's right. I had forgotten that the LRP calcs didn't include spawn timing. thanks!

**Comment by robynforrest** [comment]
Go to bed!

**Comment by jaclyncleary** [comment]
@robynforrest @cgrandin 
Update: we are able to get Fmsy values to match between ISCAM V2 (slowMSY) and the spreadsheet calculations. We are not able to reproduce the Fmsy values reported in the LRP paper- even if we set spawn timing ctl #13 (fraction of total mortality that takes place prior to spawning) to 0.0. 

I don't think we need to resolve 'why these are different' for the Res Doc but I anticipate we will be asked in the meeting. Robyn/ Chris- if something comes to mind pls let us know, otherwise we'll touch base on it again when you're back from holidays.

**Comment by robynforrest** [comment]
I used long-term average weight and mortality. I don't think it is important at this stage. I will look later if reviewer asks
