### ISSUE TITLE
iscam -retro10

### ISSUE THREAD

**Issue by Shawkshaw** [pbs-assess/gfiscam#16]
I am unable to get the iscam -retro10 to produce any new results.  It runs but produces the normal MPD results.  Am I running this correctly? or missing this updates somewhere?

**Comment by jaclyncleary** [comment]
I was also unable to run this on the mac, using: ./iscam -ind iscam.dat -retro10

**Comment by cgrandin** [comment]
It works for me, I've verified that the rep files are different and they have the correct number of years. It might be that you need a space before the number, i.e. `iscam -retro 10`

**Comment by jaclyncleary** [comment]
in the original version ISCAM would produce 10 rep files named as rep1, rep2, ..., rep10. Do we now need to run it 10 times and save each new rep file each time?

**Comment by cgrandin** [comment]
Yes

**Comment by cgrandin** [comment]
If you put a subfolder called `retrospectives` in the model directory, then 10 subfolders called `01`, `02`, etc then I will be able to write the code to bring those in. If we can agree now on directory structure it will save a ton of work reorganizing later

**Comment by Shawkshaw** [comment]
OK so do I need to run iscam -retro 1, iscam -retro 2....... iscam -retro 10 or run iscam -retro 10 10 times?

**Comment by cgrandin** [comment]
You run `iscam -retro 1` in the 01 directory, then `iscam -retro 2` in the 02 directory, etc

**Comment by jaclyncleary** [comment]
got it. thanks!

**Comment by Shawkshaw** [comment]
Thanks! I will close this now

**Comment by Shawkshaw** [comment]
I am still having trouble with the iscam -retro command.  
iscam -retro 1-5 work fine but the -retro 6-10 are giving an error in the abmb_runtime.log for all stocks AM1 and AM2: **matrix bound exceeded -- row index too high in dmatrix::operator()value was1**

I have put all the runs into the Herring\2017mcmc\retrospectives directory in the private repository.
Any ideas?

**Comment by cgrandin** [comment]
It's due to some year values in the projection file. The lines
`1) Start year for mean natural mortality rate` and
`3) Start year for average fecundity/weight-at-age in projections`
are 2013 and the end year is 2017, so that's 5 years. If we are to run retrospectives beyond that, these will have to change also to span the years of the retros.

I wish the error messages were more helpful!

**Comment by Shawkshaw** [comment]
That makes sense!  It is working now, thank you!
