### ISSUE TITLE
Allow pyr to be controlled from the pfc file at least for dd model

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/gfiscam#19]
Currently pyr is set in projection_model_dd as 
int pyr = nyr + 3  (where the numeral is one year after the catch advice you want to give. e.g., if giving catch advice for nyr+2, you need to run a 3 year projection to see the biomass resulting from your catch advice)

Make it so 
int pyr = nyr + x
where x is set in the pfc file

All the code for producing the mpd and mcmc projections will automatically update. Hardwiring has been removed.

**Comment by cgrandin** [comment]
What's the priority on this?

**Comment by robynforrest** [comment]
Low. After Herring I would say then we should do it for both ASM and DD. Give us time to test it properly
