### ISSUE TITLE
add new herring HCRs using function library (iscam_HCRs.cxx) from LandmarkFisheries

### ISSUE THREAD

**Issue by jaclyncleary** [pbs-assess/gfiscam#22]

**Comment by cgrandin** [comment]
The arguments don't exist in iscam... i.e. **future_bt3andolder** is not a variable in iscam so I cannot make a function call with it. There appears to be code missing. It is supposed to be **projected spawning biomass in kt**, so what is that ini the herring model?

**Comment by jaclyncleary** [comment]
It should be the same variable name as is used in the decision tables which is **projected spawning biomass**. The future_bt3andolder is from the old iscam tpl which Sam modified to add the EVV addition (it was just already linked into the mseRfinfish operating model so we didn't swap in the new iscam model.

**Comment by cgrandin** [comment]
Ok, I am going to use p_sbt(pyr+1) in the last_phase().

What is tmpbo ?

**Comment by jaclyncleary** [comment]
yes- p_sbt(pyr+1)  is correct

tmpbo should be **sbo - longterm average unfished spawning biomass**

(old iscam had bo and sbo, where bo was dynamic-bo - based on most recent estimates of weight-age and M)

**Comment by cgrandin** [comment]
Ok, thanks. I will code it up

**Comment by cgrandin** [comment]
Did this in the Herring SR repo instead: https://github.com/grinnellm/HerringAssess/issues/12
