### ISSUE TITLE
Output annual natural mortality and age-2 recruitment by for herring

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/gfiscam#8]
There are two additional mcmc outputs required for herring: total natural mortality by year (time-varying) and number of age-2 recruits by year. For the old iSCAM (V1), Jaclyn wrote some code to output these two as .mcmc files with one column for each year, and one row for each of the thinned mcmc output.  We use these data to make the attached plot, panels b & c – I have code to make this and bring it into the csas-latex template. These show the median as dots/lines, and credible intervals as vertical bars/shaded areas. Jaclyn has not yet written this code for the new iSCAM (V2), and we’re wondering what the best approach is. I know you now use .csv as an extension instead of .mcmc.
![storyboardam1](https://user-images.githubusercontent.com/25674027/29835726-b5642d32-8ca7-11e7-9770-db47dd0af72b.png)

**Comment by cgrandin** [comment]
I wasn't able to get this done today.. The time-varying M is also at-age so is it age-2 values we need?

**Comment by jaclyncleary** [comment]
age-2 is fine- you'll see that all ages are the same. The model actually can't implement the age-variant + time-variant estimation, even though the matrix exists to hold the estimates.

**Comment by robynforrest** [comment]
The recruits output by the model (rt) is age  2 already.

**Comment by robynforrest** [comment]
There should be an output file iscam_rt_mcmc.csv after running mceval. Note the first year of the recruits and label the x-axis accordingly

**Comment by cgrandin** [comment]
Done in commit b7073a22692667ebd6157a205a9098c033f5039e
